version: "3"

services:
  backend:
    container_name: "umbrella-backend"
    build: .
    volumes:
    - ".:/app"
    - "/app/node_modules"
    image: node
    ports:
    - "3000:3000"
    env_file: ".env"
    environment:
      - "PGHOST=postgres"
    depends_on:
      - postgres

  postgres:
    container_name: "umbrella-postgres"
    image: postgres:12
    ports:
      - "3306:3306"
    env_file: ".env"

volumes:
  data_backend_libs:
    driver: local
